export const RPC_URL = "https://rpc.qubic.org";

export const API_URL = "https://dev01.qubic.org";

export const EXPLORER_URL = "https://explorer.qubic.org";

export const DEFAULT_TX_SIZE = 144;

export const DEFAULT_TICK_OFFSET = 10;

export const ISSUER = new Map<string, string>([
  ["QX", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["QTRY", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["RANDOM", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["QUTIL", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["MLM", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["GQMPROP", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["SWATCH", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["CCF", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["QEARN", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["QVAULT", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["MSVAULT", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["QBAY", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["QSWAP", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["NOST", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["QDRAW", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["RL", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["QBOND", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["QIP", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["QRAFFLE", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFXIB"],
  ["CFB", "CFBMEMZOIDEXQAUXYYSZIURADQLAPWPMNJXQSNVQZAHYVOPYUKKJBJUCTVJL"],
  ["CODED", "CODEDBUUDDYHECBVSUONSSWTOJRCLZSWHFHZIUWVFGNWVCKIWJCSDSWGQAAI"],
  ["GARTH", "GARTHFANXMPXMDPEZFQPWFPYMHOAWTKILINCTRMVLFFVATKVJRKEDYXGHJBF"],
  ["GENESIS", "POCCZYCKTRQGHFIPWGSBLJTEQFDDVVBMNUHNCKMRACBGQOPBLURNRCBAFOBD"],
  ["MATILDA", "ZWQHZOEAWYKSGDPWWAQBAOKECCSASFCMLYZOJGBXNABXVZJZXKXOWRTFIQHC"],
  ["PORTAL", "IQUGNVFDQSLTXFJSIOPPNPZINSCDQTJVJWGRPWRTFFXMXSJIAASXOBFFBERK"],
  ["Q", "QNVPSIWLWYQXZGSMPVJTTTUKGBFCZABVUEVNMNKRDCMEQRMUWVRCSCTFDBWK"],
  ["QCAP", "QCAPWMYRSHLBJHSTTZQVCIBARVOASKDENASAKNOBRGPFWWKRCUVUAXYEZVOG"],
  ["QDOGE", "QDOGEEESKYPAICECHEAHOXPULEOADTKGEJHAVYPFKHLEWGXXZQUGIGMBUTZE"],
  ["QFT", "TFUYVBXYIYBVTEMJHAJGEJOOZHJBQFVQLTBBKMEHPEVIZFXZRPEYFUWGTIWG"],
  ["QGOLD", "QGRNNKNCTTKVBAACUANWEGRXGPGDOHXYZNMKGEUZSEXBNBBWUBJHAGDGWCSH"],
  ["QHEART", "SSGXSLSXFEJOOBTZWVDSRCEFGXNDYUVDXMQALXLBXGDCRXTKFZIOTGZFUNXO"],
  ["QMINE", "QMINEQQXYBEGBHNSUPOUYDIQKZPCBPQIIHUUZMCPLBPCCAIARVZBTYKGFCWM"],
  ["QSILVER", "EQZIDZELUKGHICLIEXLBMBMXRNPCXGEAZCGGSQCOFBRJJUOKUWBXDEZBGNKJ"],
  ["QST", "QMHJNLMQRIBIREFIWVKYQELBFARBTDNYKIOBOFFYFGJYZSXJBVGBSUQGHSAM"],
  ["QTC", "YCNPBGPGMJYCWGBJKQWLNRNKKJMBKQORLRKOSFUOWAWNXJHBLGTGFRRELGEK"],
  ["QWALLET", "QWALLETSGQVAGBHUCVVXWZXMBKQBPQQSHRYKZGEJWFVNUFCEDDPRMKTAUVHA"],
  ["QXMR", "QXMRTKAIIGLUREPIQPCMHCKWSIPDTUYFCFNYXQLTECSUJVYEMMDELBMDOEYB"],
  ["QXTRADE", "QXTRMABNAJWNQBKYYNUNVYAJAQMDLIKOFXNGTRVYRDQMNZNNMZDGBDNGYMRM"],
  ["SATOSHI", "WZEQKJXIWECRGHSRJJDRGFREYMBCTKQGPWEYGLQMPGMKNRZNCZGPFGMCGANI"],
  ["VSTB001", "VALISTURNWYFQAMVLAKJVOKJQKKBXZZFEASEYCAGNCFMZARJEMMFSESEFOWM"],
]);

export const THEME_LIST = [
  {
    label: "Default",
    value: "default",
  },
  {
    label: "UnTrue",
    value: "untrue",
  },
  {
    label: "Adj",
    value: "adj",
  },
  {
    label: "Purple Dark V2",
    value: "purple-dark-v2",
  },
  {
    label: "Midnight Tokyo",
    value: "midnight-tokyo",
  },
  {
    label: "Brutal",
    value: "brutal",
  },
  {
    label: "Rose",
    value: "rose",
  },
];
